### ISSUE TITLE
master branch missing from cgit repo

### ISSUE THREAD

**Issue by funeeldy** [metajack/cgit#1]
I have 8 repositories displayed in my cgit setup.  one of them is missing the master branch in the list of refs and the switch drop down box.  The master branch is definitely available in the repo when I make a clone, so why is it missing on the cgit web site?  Thanks.

**Comment by metajack** [comment]
This cgit fork is not the canonical one, and hasn't been updated in probably 2 years. I was using it to test and submit some bugs upstream.

The canonical location is http://hjemli.net/git/cgit/

I'd try grabbing the latest version from there and if  you still experience the problem, e-mail the author.
